### ISSUE TITLE
Nit in license

### ISSUE THREAD

**Issue by davelab6** [twardoch/fonttools-utils#1]
You lost the spaces off the start of the first line of https://github.com/twardoch/fonttools-utils/blob/master/LICENSE

**Comment by twardoch** [comment]
Huh? Don't see it. Screenshot please. 

Actually, THAT license file is the one provided by Github, I hadnt touched that file myself. I only did inside the MacOSX... tool folder. I made one repo where I'll be collecting more tools, each in a subfolder.

**Comment by davelab6** [comment]
> THAT license file is the one provided by Github

Ah, interesting! I'll file a bug there too

**Comment by davelab6** [comment]
BTW github acknowledged their error and fixed it
