### ISSUE TITLE
[pyftfeatfreeze]: Why do CFFs get nameID 4 = nameID 6?

### ISSUE THREAD

**Issue by madig** [twardoch/fonttools-utils#13]
Currently working on updating the code, stumbled over this. Is there a technical reason to do https://github.com/twardoch/fonttools-utils/blob/2b77a32b2405229650fd2d6115828a30fb2b9f6e/pyftfeatfreeze/pyftfeatfreeze.py#L369-L373?

**Comment by twardoch** [comment]
There was an old requirement by Adobe to do this. Like in 2000-2006 or so. No longer needed
