### ISSUE TITLE
opentype-feature-freezer not found on pypi

### ISSUE THREAD

**Issue by sewkokot** [twardoch/fonttools-utils#15]
I tried to install opentype-feature-freezer with:
`pip install opentype-feature-freezer`

and got:

```
Collecting opentype-feature-freezer
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/opentype-feature-freezer/
```

**Comment by juandelperal** [comment]
Same here!
How can I install the package? Thanks

**Comment by twardoch** [comment]
There is currently no package and no installer, nothing that works with pip

**Comment by juandelperal** [comment]
OK Adam, and how do I download and run the script?
```
 (venv)  juan@Juan  ~/sites/fonttools-utils   master  python pyftfeatfreeze/src/opentype_feature_freezer/cli.py
Traceback (most recent call last):
  File "pyftfeatfreeze/src/opentype_feature_freezer/cli.py", line 7, in <module>
    import opentype_feature_freezer
ModuleNotFoundError: No module named 'opentype_feature_freezer'
```

**Comment by agargiulo** [comment]
bump, would like to see the pypi package reappear as well.

**Comment by twardoch** [comment]
OK, I’ve refactored the repo and made it standalone under https://github.com/twardoch/fonttools-opentype-feature-freezer — one more step towards putting it on Pypi. 

I’ve changed the project URL, so you can now install it from git:

```
pip install --upgrade git+https://github.com/twardoch/fonttools-opentype-feature-freezer
```

**Comment by juandelperal** [comment]
Wonderful, thanks Adam
