### ISSUE TITLE
When tried to install with pipx, got ERROR: Could not find...

### ISSUE THREAD

**Issue by vostojin** [twardoch/fonttools-utils#16]
When tried to install with pipx, got **ERROR: Could not find...**

    % pipx install opentype-feature-freezer

    ERROR: Could not find a version that satisfies the requirement opentype-feature-freezer (from versions: none)
    ERROR: No matching distribution found for opentype-feature-freezer

**Comment by Myrronth** [comment]
Same here. Did you manage to get it installed @vostojin ?

**Comment by vostojin** [comment]
No @Myrronth. I haven't tried again, just downloaded this repo and run 'manually' like this:
```shell
% python PATH_TO_FONTTOOLS_UTILS/pyftfeatfreeze/src/opentype_feature_freezer/cli.py OPTIONS
```

**Comment by Myrronth** [comment]
Thanks a lot! Had to move cli.py on level up. After that it worked 👍 (I do not know python, maybe I’m missing something.)

**Comment by twardoch** [comment]
OK, I’ve refactored the repo and made it standalone under https://github.com/twardoch/fonttools-opentype-feature-freezer — one more step towards putting it on Pypi. 

I’ve changed the project URL, so you can now install it from git:

```
pip install --upgrade git+https://github.com/twardoch/fonttools-opentype-feature-freezer
```
