### ISSUE TITLE
WARNING: No 'GSUB' table found in ..., nothing to do!

### ISSUE THREAD

**Issue by sharpjs** [twardoch/fonttools-utils#21]
Some of the files in [JetBrains Mono v2.200](https://github.com/JetBrains/JetBrainsMono/releases/tag/v2.200) fail with `pyftfeatfreeze`.

Specifically, [I use](https://github.com/sharpjs/JetBrainsMonoSlashed/blob/master/build.sh#L70) the command:

```
pyftfeatfreeze -f zero -i -S -U Slashed "$src" "$dst"
```

to turn on the font's (undocumented) slashed zero.

With that font's `NL` (non-ligature) variants, `pyftfreeze` fails with, for example:

```
WARNING: No 'GSUB' table found in JetBrainsMonoNL-Bold.ttf
```

I'm not super knowledgeable about OTF/TTF internals.  Is it possible to turn on the `zero` feature without a `GSUB` table present in the font?

**Comment by tphinney** [comment]
The current regular JetBrainsMono build has the zero feature as expected (and it is in the GSUB table, which is kind of the only plausible way to do it).

Probably those non-ligature variants are also lacking the zero feature, and indeed the entire GSUB table. So of course, they will fail.

**Comment by sharpjs** [comment]
> and it is in the GSUB table, which is kind of the only plausible way to do it

Thanks.  I will ask the JetBrains Mono authors to remedy the table's absence in the `NL` variants.

I'll go ahead and self-close this issue, since `pyftfeatfreeze` appears to be working as designed.  Thanks again!
