### ISSUE TITLE
Apply freeze to an entire family?

### ISSUE THREAD

**Issue by jonvog** [twardoch/fonttools-utils#25]
I don't know if I missed something in the documentation, but is it possible to apply the freezing of a particular feature to the whole family in one pass?

**Comment by twardoch** [comment]
That depends on the operating system you are using.

**Comment by jonvog** [comment]
I am on Windows 10 Pro...

**Comment by twardoch** [comment]
You can make a very simple .bat script, see https://stackoverflow.com/questions/14237548/batch-script-run-command-on-each-file-in-directory

**Comment by jonvog** [comment]
Great, thanks!
