### ISSUE TITLE
Got an error.

### ISSUE THREAD

**Issue by GalacticAir** [twardoch/fonttools-utils#28]
usage: OTFeatureFreezer.exe [-h] [-o [OUTPATH]] [-f FEATURES] [-s SCRIPT]
                            [-l LANG] [-z] [-S] [-U USESUFFIX]
                            [-R REPLACENAMES] [-i] [-r] [-n] [-v]
                            inpath
OTFeatureFreezer.exe: error: unrecognized arguments: -- C:\Users\parent\Downloads\Inter-Regular.otf

Anyone knows what might have caused this?

**Comment by kenmcd** [comment]
Take a look at the examples right above where you copied that code.
The examples show the proper syntax.
You are including stuff which should not be there - hence the error message.

**Comment by GalacticAir** [comment]
> Take a look at the examples right above where you copied that code. The examples show the proper syntax. You are including stuff which should not be there - hence the error message.

**Comment by GalacticAir** [comment]
I see, thank you!

**Comment by GalacticAir** [comment]
OMGOSH THANK YOU SO MUCH IT WORKED!
